### ISSUE TITLE
Microphone not working on archlinux

### ISSUE THREAD

**Issue by MartinFillon** [IsmaelMartinez/teams-for-linux#1104]
**Describe the bug**
The microphone is not detected on archlinux with pipewire and alsa

**To Reproduce**

**Expected behavior**
to be able to talk

**Screenshots**
```
Audio:
  Device-1: Intel Tiger Lake-LP Smart Sound Audio vendor: Dell
    driver: snd_hda_intel v: kernel bus-ID: 00:1f.3 chip-ID: 8086:a0c8
    class-ID: 0401
  API: ALSA v: k6.7.3-arch1-2 status: kernel-api
    tools: alsactl,alsamixer,amixer
  Server-1: sndiod v: N/A status: off tools: aucat,midicat,sndioctl
  Server-2: PipeWire v: 1.0.3 status: active with: 1: pipewire-pulse
    status: active 2: wireplumber status: active 3: pipewire-alsa
    type: plugin 4: pw-jack type: plugin tools: pactl,pw-cat,pw-cli,wpctl
```

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Installation package yay git version
 - Version last commit

**Additional context**
