### ISSUE TITLE
Automate flathub upload

### ISSUE THREAD

**Issue by IsmaelMartinez** [IsmaelMartinez/teams-for-linux#1174]
**Is your feature request related to a problem? Please describe.**
Currently the upload process for flathub is manually done

**Describe the solution you'd like**
For this to be automatically done 

**Describe alternatives you've considered**
Getting more people to be able to manually create a release is also a good temporary alternative

**Additional context**

To do a release, please go to https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux and fork it.

Send a PR by changing the 2 files.

*    com.github.IsmaelMartinez.teams_for_linux.appdata.xml which contains release information. Currently flathub and this repo are having duplicate files. This is something we need to improve.
*    com.github.IsmaelMartinez.teams_for_linux.yml. This is the flatpak build manifest file. Usually this is modified

```
 sources:
      - type: file
        url: https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.4.16/teams-for-linux_1.4.16_amd64.deb
        sha256: 8507a00f3a562abafa8382d235027eb361fb0464ae01db242266e17e226cd968
```

Flathub people then review the PR and either accept it and merge it or not.
